# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
yml: version
# Site settings
yml:
  gems:
    - jekyll-seo-tag
title: Abuse Ombudsman GitHub Page
email: abuse.ombudsman@gmail.com
description: "abuse.ombudsman@gmail.com defiende el derecho a salvarse de la humillaciòn
y la desvastación dela privada en la pública, pero cree en la evolución y en los mecanismos
de la defensa del conjunto de la popular defensa de la integridad propia y ajena, por eso
somos positivistas y recalcamos que lo peor es la sujestiòn!Free IPTV, 700+ channels, many
HD, germans, polish and rusians. List available 700+.!.!.!"
baseurl: "" 
url: "https://abuseombudsman.github.io" # the base hostname & protocol for your site
author: (ND)CULTURA
twitter:
  username: idiaminx
facebook:
  publisher: https://www.facebook.com/AbuseOmbudsman-1118760924882808/
logo: assets/CULTURA.png
github_username:  abuseombudsman


# Build settings
markdown: kramdown
theme: minima

